Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/FileName:
  Exclude:
    - 'Gemfile'

AllCops:
  TargetRubyVersion: 2.4
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'config/unicorn.rb'
    - 'db/**/*'
    - 'vendor/bundle/**/*'
