source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'bcrypt-ruby'
gem 'figaro'
gem 'jsonapi-rails'
gem 'pg'
gem 'puma', '~> 3.7'
gem 'rack-cors'
gem 'rails', '~> 5.1.0'

# google signin
gem 'google-api-client'
gem 'jwt'
gem 'signet'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'brakeman'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'pry-rails'
  gem 'rubocop'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'simplecov', require: false
  gem 'mocha'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
